import moment from 'moment';

export default {
  128: {
    _id: '128',
    title: 'Read More Books',
    date: moment('2018-04-04T09:16:51.772Z'),
    description: '"The Philosophy of Andy Warhol"\nI had amazing time reading this book',
    track: 0,
    likes: [
      '4',
      '5',
      '6',
    ],
    goalId: '50055',
    keyResults: [
      {
        _id: '1',
        title: 'Read a book',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 1,
        delta: 1,
      },
    ],
    progress: 100,
    delta: 100,
    creator: {
      _id: '5',
      firstName: 'Pavel',
      lastName: 'Kalugin',
      image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
    },
    status: 'Open',
  },
  658: {
    _id: '658',
    title: 'Create OKR Product During Startup Summer',
    date: moment('2018-04-04T13:53:16.813Z'),
    description: 'Crushed design, add bugs',
    track: 1,
    likes: ['1',
      '2',
      '9',
      '10',
    ],
    goalId: '1',
    keyResults: [
      {
        _id: '16616',
        title: 'Present Template',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 80,
        delta: 0,
      },
      {
        _id: '5068',
        title: 'Implement Design',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 73,
        delta: -11,
      },
      {
        _id: '1719',
        title: 'Connect Pages To Each Other',
        measure: {
          type: 'numeric',
          from: 0,
          to: 20,
        },
        progress: 20,
        delta: 2,
      },
      {
        _id: '8178',
        title: 'Test Every Single UI Part',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
        delta: 0,
      },
      {
        _id: '4728',
        title: 'Present Product on Demo Day',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 0,
        delta: 0,
      },
    ],
    progress: 51,
    delta: 0,
    creator: {
      _id: '7',
      firstName: 'Evgeny',
      lastName: 'Marushko',
      image: 'https://trello-avatars.s3.amazonaws.com/86cdd1e9a00b6877cf3bf52f68dcd664/170.png',
    },
    status: 'Open',
  },
  1048: {
    _id: '1048',
    title: 'Succesfully Organise Startup Winter',
    date: moment('2018-04-04T09:14:46.478Z'),
    description: 'Half lectures are read',
    track: 0,
    likes: [
      '1',
      '6',
      '7',
      '8',
      '9',
      '10',
    ],
    goalId: '2',
    keyResults: [
      {
        _id: '64504',
        title: 'Prepare Place and Equipment',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 1,
        delta: 1,
      },
      {
        _id: '3385',
        title: 'Read Lectures & Review Tasks',
        measure: {
          type: 'numeric',
          from: 0,
          to: 17,
        },
        progress: 10,
        delta: 10,
      },
      {
        _id: '7745',
        title: 'Create OKR Product',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
        delta: 0,
      },
      {
        _id: '7512',
        title: 'Create Cycle Service Product',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
        delta: 0,
      },
      {
        _id: '892',
        title: 'Collect Feedback From Students',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
        delta: 0,
      },
    ],
    progress: 32,
    delta: 32,
    creator: {
      _id: '1',
      firstName: 'Andrew',
      lastName: 'Orsich',
      image: 'https://trello-avatars.s3.amazonaws.com/23616a42b3226927d6ab9b2fc5905e19/original.png',
    },
    status: 'Open',
  },
  2046: {
    _id: '2046',
    title: 'Spend More Time With Friends & Family',
    date: moment('2018-04-04T09:18:17.427Z'),
    description: 'Spend weekend in an amusement park with my girlfriend',
    track: 0,
    likes: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
    ],
    goalId: '51963',
    keyResults: [
      {
        _id: '1',
        title: 'Meet with friends',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 1,
        delta: 1,
      },
      {
        _id: '2',
        title: 'Phone parents once a week',
        measure: {
          type: 'numeric',
          from: 0,
          to: 12,
        },
        progress: 4,
        delta: 4,
      },
    ],
    progress: 67,
    delta: 67,
    creator: {
      _id: '5',
      firstName: 'Pavel',
      lastName: 'Kalugin',
      image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
    },
    status: 'Open',
  },
  2786: {
    _id: '2786',
    title: 'Read More Books',
    date: moment('2018-04-04T09:17:29.700Z'),
    description: '"The Philosophy of Andy Warhol"\nI had amazing time reading this book',
    track: 0,
    likes: [
      '1',
      '2',
      '3',
      '8',
      '9',
      '10',
    ],
    goalId: '50055',
    keyResults: [
      {
        _id: '1',
        title: 'Read a book',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 1,
        delta: 1,
      },
    ],
    progress: 100,
    delta: 100,
    creator: {
      _id: '5',
      firstName: 'Pavel',
      lastName: 'Kalugin',
      image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
    },
    status: 'Close',
  },
  3128: {
    _id: '3128',
    title: 'Become a Full Stack Developer ',
    date: moment('2018-04-04T09:31:17.548Z'),
    description: 'Made some useful features',
    track: 0,
    likes: [
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
    ],
    goalId: '50677',
    keyResults: [
      {
        _id: '78522',
        title: 'Learn Frontend, listen to 9 lectures',
        measure: {
          type: 'numeric',
          from: 0,
          to: 9,
        },
        progress: 9,
        delta: 0,
      },
      {
        _id: '3105',
        title: 'Learn Backend',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 75,
        delta: 15,
      },
      {
        _id: '6033',
        title: 'Learn devOps',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 1,
        delta: 0,
      },
      {
        _id: '92',
        title: 'Take active part in product development',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 50,
        delta: 15,
      },
    ],
    progress: 82,
    delta: 8,
    creator: {
      _id: '5',
      firstName: 'Pavel',
      lastName: 'Kalugin',
      image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
    },
    status: 'Open',
  },
  3154: {
    _id: '3154',
    title: 'Create OKR Product During Startup Summer',
    date: moment('2018-04-04T13:53:37.301Z'),
    description: 'Make tests and think about Demo Day',
    track: 0,
    likes: [
      '1',
      '2',
      '3',
      '4',
      '8',
    ],
    goalId: '1',
    keyResults: [
      {
        _id: '16616',
        title: 'Present Template',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 80,
        delta: 0,
      },
      {
        _id: '5068',
        title: 'Implement Design',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 90,
        delta: 17,
      },
      {
        _id: '1719',
        title: 'Connect Pages To Each Other',
        measure: {
          type: 'numeric',
          from: 0,
          to: 20,
        },
        progress: 20,
        delta: 0,
      },
      {
        _id: '8178',
        title: 'Test Every Single UI Part',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 61,
        delta: 61,
      },
      {
        _id: '4728',
        title: 'Present Product on Demo Day',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 0,
        delta: 0,
      },
    ],
    progress: 67,
    delta: 16,
    creator: {
      _id: '2',
      firstName: 'Nikita',
      lastName: 'Borww',
      image: 'https://trello-avatars.s3.amazonaws.com/a34f0b51cd60f764c71e7b0965c10a54/original.png',
    },
    status: 'Open',
  },
  3459: {
    _id: '3459',
    title: 'Succesfully Organise Startup Winter',
    date: moment('2018-04-04T09:15:32.021Z'),
    description: 'All lectures are red. Students have started working on projects',
    track: 0,
    likes: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
    ],
    goalId: '2',
    keyResults: [
      {
        _id: '64504',
        title: 'Prepare Place and Equipment',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 1,
        delta: 0,
      },
      {
        _id: '3385',
        title: 'Read Lectures & Review Tasks',
        measure: {
          type: 'numeric',
          from: 0,
          to: 17,
        },
        progress: 17,
        delta: 7,
      },
      {
        _id: '7745',
        title: 'Create OKR Product',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 10,
        delta: 10,
      },
      {
        _id: '7512',
        title: 'Create Cycle Service Product',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 8,
        delta: 8,
      },
      {
        _id: '892',
        title: 'Collect Feedback From Students',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
        delta: 0,
      },
    ],
    progress: 44,
    delta: 12,
    creator: {
      _id: '8',
      firstName: 'Michael',
      lastName: 'Slizenko',
      image: 'https://trello-avatars.s3.amazonaws.com/ac3a1fb8b38af4218aff0873aae688b7/170.png',
    },
    status: 'Open',
  },
  3627: {
    _id: '3627',
    title: 'Create OKR Product During Startup Summer',
    date: moment('2018-04-04T13:52:17.455Z'),
    description: 'Complete team pages and input forms',
    track: 0,
    likes: [
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
    ],
    goalId: '1',
    keyResults: [
      {
        _id: '16616',
        title: 'Present Template',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 80,
        delta: 0,
      },
      {
        _id: '5068',
        title: 'Implement Design',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 51,
        delta: 9,
      },
      {
        _id: '1719',
        title: 'Connect Pages To Each Other',
        measure: {
          type: 'numeric',
          from: 0,
          to: 20,
        },
        progress: 14,
        delta: 8,
      },
      {
        _id: '8178',
        title: 'Test Every Single UI Part',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
        delta: 0,
      },
      {
        _id: '4728',
        title: 'Present Product on Demo Day',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 0,
        delta: 0,
      },
    ],
    progress: 41,
    delta: 10,
    creator: {
      _id: '4',
      firstName: 'Max',
      lastName: 'Starling',
      image: 'https://ca.slack-edge.com/T1MKTR0RX-U8WAH2YJH-96ec2fb31862-512',
    },
    status: 'Open',
  },
  3829: {
    _id: '3829',
    title: 'Create OKR Product During Startup Summer',
    date: moment('2018-04-04T13:51:33.192Z'),
    description: 'Complete navigation, header and goals',
    track: 0,
    likes: ['1',
      '2',
      '3',
      '4',
      '8',
      '11',
      '12',
      '13',
    ],
    goalId: '1',
    keyResults: [
      {
        _id: '16616',
        title: 'Present Template',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 80,
        delta: 0,
      },
      {
        _id: '5068',
        title: 'Implement Design',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 30,
        delta: 30,
      },
      {
        _id: '1719',
        title: 'Connect Pages To Each Other',
        measure: {
          type: 'numeric',
          from: 0,
          to: 20,
        },
        progress: 2,
        delta: 2,
      },
      {
        _id: '8178',
        title: 'Test Every Single UI Part',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
        delta: 0,
      },
      {
        _id: '4728',
        title: 'Present Product on Demo Day',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 0,
        delta: 0,
      },
    ],
    progress: 24,
    delta: 8,
    creator: {
      _id: '5',
      firstName: 'Pavel',
      lastName: 'Kalugin',
      image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
    },
    status: 'Open',
  },
  5007: {
    _id: '5007',
    title: 'Become a Full Stack Developer ',
    date: moment('2018-04-04T09:29:07.037Z'),
    description: 'Learned backend a little and tools like docker, webpack, ...',
    track: 0,
    likes: [
      '1',
      '2',
      '3',
      '4',
      '8',
      '9',
      '10',
    ],
    goalId: '50677',
    keyResults: [
      {
        _id: '78522',
        title: 'Learn Frontend, listen to 9 lectures',
        measure: {
          type: 'numeric',
          from: 0,
          to: 9,
        },
        progress: 9,
        delta: 0,
      },
      {
        _id: '3105',
        title: 'Learn Backend',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 60,
        delta: 60,
      },
      {
        _id: '6033',
        title: 'Learn devOps',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 1,
        delta: 1,
      },
      {
        _id: '92',
        title: 'Take active part in product development',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
        delta: 0,
      },
    ],
    progress: 65,
    delta: 40,
    creator: {
      _id: '5',
      firstName: 'Pavel',
      lastName: 'Kalugin',
      image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
    },
    status: 'Open',
  },
  6028: {
    _id: '6028',
    title: 'Succesfully Organise Startup Winter',
    date: moment('2018-04-04T09:16:15.092Z'),
    description: '2 days due Demo Day',
    track: 0,
    likes: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '9',
      '10',
    ],
    goalId: '2',
    keyResults: [
      {
        _id: '64504',
        title: 'Prepare Place and Equipment',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 1,
        delta: 0,
      },
      {
        _id: '3385',
        title: 'Read Lectures & Review Tasks',
        measure: {
          type: 'numeric',
          from: 0,
          to: 17,
        },
        progress: 17,
        delta: 0,
      },
      {
        _id: '7745',
        title: 'Create OKR Product',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 91,
        delta: 61,
      },
      {
        _id: '7512',
        title: 'Create Cycle Service Product',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 83,
        delta: 37,
      },
      {
        _id: '892',
        title: 'Collect Feedback From Students',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
        delta: 0,
      },
    ],
    progress: 75,
    delta: 19,
    creator: {
      _id: '5',
      firstName: 'Pavel',
      lastName: 'Kalugin',
      image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
    },
    status: 'Open',
  },
  6038: {
    _id: '6038',
    title: 'Become a Full Stack Developer ',
    date: moment('2018-04-04T09:28:18.350Z'),
    description: 'Listened frontend lectures',
    track: 0,
    likes: [
      '1',
      '2',
      '5',
      '6',
      '7',
      '10',
    ],
    goalId: '50677',
    keyResults: [
      {
        _id: '78522',
        title: 'Learn Frontend, listen to 9 lectures',
        measure: {
          type: 'numeric',
          from: 0,
          to: 9,
        },
        progress: 9,
        delta: 9,
      },
      {
        _id: '3105',
        title: 'Learn Backend',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
        delta: 0,
      },
      {
        _id: '6033',
        title: 'Learn devOps',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 0,
        delta: 0,
      },
      {
        _id: '92',
        title: 'Take active part in product development',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
        delta: 0,
      },
    ],
    progress: 25,
    delta: 25,
    creator: {
      _id: '5',
      firstName: 'Pavel',
      lastName: 'Kalugin',
      image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
    },
    status: 'Open',
  },
  8052: {
    _id: '8052',
    title: 'Become a Full Stack Developer ',
    date: moment('2018-04-04T09:29:57.901Z'),
    description: 'Started working on project, improved backend knowledge.',
    track: 0,
    likes: [
      '1',
      '2',
      '3',
      '8',
      '9',
      '10',
    ],
    goalId: '50677',
    keyResults: [
      {
        _id: '78522',
        title: 'Learn Frontend, listen to 9 lectures',
        measure: {
          type: 'numeric',
          from: 0,
          to: 9,
        },
        progress: 9,
        delta: 0,
      },
      {
        _id: '3105',
        title: 'Learn Backend',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 60,
        delta: 0,
      },
      {
        _id: '6033',
        title: 'Learn devOps',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 1,
        delta: 0,
      },
      {
        _id: '92',
        title: 'Take active part in product development',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 35,
        delta: 35,
      },
    ],
    progress: 74,
    delta: 9,
    creator: {
      _id: '5',
      firstName: 'Pavel',
      lastName: 'Kalugin',
      image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
    },
    status: 'Open',
  },
  8608: {
    _id: '8608',
    title: 'Succesfully Organise Startup Winter',
    date: moment('2018-04-04T09:15:48.652Z'),
    description: 'First Demo Presentation',
    track: 0,
    likes: [
      '1',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '10',
    ],
    goalId: '2',
    keyResults: [
      {
        _id: '64504',
        title: 'Prepare Place and Equipment',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 1,
        delta: 0,
      },
      {
        _id: '3385',
        title: 'Read Lectures & Review Tasks',
        measure: {
          type: 'numeric',
          from: 0,
          to: 17,
        },
        progress: 17,
        delta: 0,
      },
      {
        _id: '7745',
        title: 'Create OKR Product',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 30,
        delta: 20,
      },
      {
        _id: '7512',
        title: 'Create Cycle Service Product',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 46,
        delta: 38,
      },
      {
        _id: '892',
        title: 'Collect Feedback From Students',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
        delta: 0,
      },
    ],
    progress: 56,
    delta: 12,
    creator: {
      _id: '2',
      firstName: 'Nikita',
      lastName: 'Borww',
      image: 'https://trello-avatars.s3.amazonaws.com/a34f0b51cd60f764c71e7b0965c10a54/original.png',
    },
    status: 'Open',
  },
  8610: {
    _id: '8610',
    title: 'Create OKR Product During Startup Summer',
    date: moment('2018-04-04T13:51:53.888Z'),
    description: 'Complete main pages',
    track: 0,
    likes: ['1',
      '12',
      '13',
    ],
    goalId: '1',
    keyResults: [
      {
        _id: '16616',
        title: 'Present Template',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 80,
        delta: 0,
      },
      {
        _id: '5068',
        title: 'Implement Design',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 42,
        delta: 12,
      },
      {
        _id: '1719',
        title: 'Connect Pages To Each Other',
        measure: {
          type: 'numeric',
          from: 0,
          to: 20,
        },
        progress: 6,
        delta: 4,
      },
      {
        _id: '8178',
        title: 'Test Every Single UI Part',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
        delta: 0,
      },
      {
        _id: '4728',
        title: 'Present Product on Demo Day',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 0,
        delta: 0,
      },
    ],
    progress: 31,
    delta: 7,
    creator: {
      _id: '6',
      firstName: 'Polina',
      lastName: 'Rudenko',
      image: 'https://trello-avatars.s3.amazonaws.com/ea220d8c67e39a887bb45ec1d4f7ff61/original.png',
    },
    status: 'Open',
  },
  8620: {
    _id: '8620',
    title: 'Create OKR Product During Startup Summer',
    date: moment('2018-04-04T13:51:01.697Z'),
    description: 'Presentation was very nice. We are inspired and ready to make cool product',
    track: 0,
    likes: [
      '1',
      '2',
    ],
    goalId: '1',
    keyResults: [
      {
        _id: '16616',
        title: 'Present Template',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 80,
        delta: 80,
      },
      {
        _id: '5068',
        title: 'Implement Design',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
        delta: 0,
      },
      {
        _id: '1719',
        title: 'Connect Pages To Each Other',
        measure: {
          type: 'numeric',
          from: 0,
          to: 20,
        },
        progress: 0,
        delta: 0,
      },
      {
        _id: '8178',
        title: 'Test Every Single UI Part',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
        delta: 0,
      },
      {
        _id: '4728',
        title: 'Present Product on Demo Day',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 0,
        delta: 0,
      },
    ],
    progress: 16,
    delta: 16,
    creator: {
      _id: '5',
      firstName: 'Pavel',
      lastName: 'Kalugin',
      image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
    },
    status: 'Open',
  },
  8706: {
    _id: '8706',
    title: 'Read More Books',
    date: moment('2018-04-04T09:17:08.731Z'),
    description: '',
    track: 0,
    likes: [
      '1',
      '2',
      '3',
      '4',
      '9',
      '10',
    ],
    goalId: '50055',
    keyResults: [
      {
        _id: '1',
        title: 'Read a book',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 0,
        delta: -1,
      },
    ],
    progress: 0,
    delta: -100,
    creator: {
      _id: '5',
      firstName: 'Pavel',
      lastName: 'Kalugin',
      image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
    },
    status: 'Open',
  },
  9657: {
    _id: '9657',
    title: 'Create OKR Product During Startup Summer',
    date: moment('2018-04-04T13:52:53.142Z'),
    description: 'Complete all workflow components',
    track: 0,
    likes: ['1',
      '2',
      '3',
      '4',
      '10',
      '11',
      '12',
      '13',
    ],
    goalId: '1',
    keyResults: [
      {
        _id: '16616',
        title: 'Present Template',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 80,
        delta: 0,
      },
      {
        _id: '5068',
        title: 'Implement Design',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 84,
        delta: 33,
      },
      {
        _id: '1719',
        title: 'Connect Pages To Each Other',
        measure: {
          type: 'numeric',
          from: 0,
          to: 20,
        },
        progress: 18,
        delta: 4,
      },
      {
        _id: '8178',
        title: 'Test Every Single UI Part',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
        delta: 0,
      },
      {
        _id: '4728',
        title: 'Present Product on Demo Day',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 0,
        delta: 0,
      },
    ],
    progress: 51,
    delta: 10,
    creator: {
      _id: '3',
      firstName: 'Aliona',
      lastName: 'Mozol',
      image: 'https://trello-avatars.s3.amazonaws.com/3695f09f8fdff0ddb23cfa10b5be1e30/original.png',
    },
    status: 'Open',
  },
  57313: {
    _id: '57313',
    title: 'Make a step toward setting up your personal goals',
    date: moment('2018-04-04T09:13:45.059Z'),
    description: 'Welcome to TakeBuddy! Get started by reviewing and setting your goals.',
    track: 0,
    likes: [
      '1',
      '2',
      '7',
      '8',
      '10',
    ],
    goalId: '88200',
    keyResults: [
      {
        _id: '1',
        title: 'Sign up for TakeBuddy',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 1,
        delta: 1,
      },
    ],
    progress: 100,
    delta: 100,
    creator: {
      _id: '5',
      firstName: 'Pavel',
      lastName: 'Kalugin',
      image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
    },
    status: 'Close',
  },
};
