const LOGO_PARALECT = 'https://pp.userapi.com/c840525/v840525921/6092e/7-YxPOAhv2g.jpg';

export default {
  1: {
    _id: '1',
    type: 'Group',
    name: 'Paralect',
    description: 'Paralect is a company fully devoted to the technology of creating custom software.',
    privacy: 'Private',
    image: LOGO_PARALECT,
    creator: '1',
    parentTeam: null,
    childTeams: ['2', '3'],
    openGoals: ['2', '3', '5'],
    closeGoals: [],
    members: [
      {
        _id: '1',
        firstName: 'Andrew',
        lastName: 'Orsich',
        username: 'andreworsich',
        image: 'https://trello-avatars.s3.amazonaws.com/23616a42b3226927d6ab9b2fc5905e19/original.png',
        role: 'admin',
      },
      {
        _id: '2',
        firstName: 'Nikita',
        lastName: 'Borww',
        username: 'SobakaSlava',
        image: 'https://trello-avatars.s3.amazonaws.com/a34f0b51cd60f764c71e7b0965c10a54/original.png',
        role: 'member',
      },
      {
        _id: '3',
        firstName: 'Aliona',
        lastName: 'Mozol',
        username: 'alionamozol',
        image: 'https://trello-avatars.s3.amazonaws.com/3695f09f8fdff0ddb23cfa10b5be1e30/original.png',
        role: 'member',
      },
      {
        _id: '4',
        firstName: 'Max',
        lastName: 'Starling',
        username: 'maxstarling',
        image: 'https://ca.slack-edge.com/T1MKTR0RX-U8WAH2YJH-96ec2fb31862-512',
        role: 'member',
      },
      {
        _id: '5',
        firstName: 'Pavel',
        lastName: 'Kalugin',
        username: 'pavelkalugin',
        image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
        email: 'p.kalugin@gmail.com',
        role: 'member',
      },
      {
        _id: '6',
        firstName: 'Polina',
        lastName: 'Rudenko',
        username: 'polinarudenko',
        image: 'https://ca.slack-edge.com/T1MKTR0RX-U8W2KE6AX-ad9c578b5944-512',
        role: 'member',
      },
      {
        _id: '7',
        firstName: 'Evgeny',
        lastName: 'Marushko',
        username: 'evgenymarushko',
        image: 'https://trello-avatars.s3.amazonaws.com/86cdd1e9a00b6877cf3bf52f68dcd664/170.png',
        role: 'member',
      },
      {
        _id: '8',
        firstName: 'Michael',
        lastName: 'Slizenko',
        username: 'slizenko',
        image: 'https://trello-avatars.s3.amazonaws.com/ac3a1fb8b38af4218aff0873aae688b7/170.png',
        role: 'admin',
      },
      {
        _id: '9',
        firstName: 'Nikita',
        lastName: 'Goncharov',
        username: 'nikitagoncharov',
        image: 'https://ca.slack-edge.com/T1MKTR0RX-U8W543H0C-16591591a0b2-512',
        role: 'member',
      },
      {
        _id: '10',
        firstName: 'Anna',
        lastName: 'Korosteleva',
        username: 'annakorosteleva',
        image: 'https://ca.slack-edge.com/T1MKTR0RX-U8VKLL4E4-efdd82438db6-512',
        role: 'member',
      },
      {
        _id: '11',
        firstName: 'Max',
        lastName: 'Mabius',
        username: 'maxmabius',
        image: 'https://trello-avatars.s3.amazonaws.com/b9899ed97c146e9ab0f261bdc6b3c8ea/170.png',
        role: 'member',
      },
      {
        _id: '12',
        firstName: 'Eugene',
        lastName: 'Shved',
        username: 'eugeneshved',
        image: 'https://ca.slack-edge.com/T1MKTR0RX-U8VL926SV-021c09335023-512',
        role: 'member',
      },
      {
        _id: '13',
        firstName: 'Nikolai',
        lastName: 'Yurkevich',
        username: 'nikolaiyourkevich',
        image: 'https://ca.slack-edge.com/T1MKTR0RX-U8VPH7X6C-745485839eaf-512',
        role: 'member',
      },
      {
        _id: '14',
        firstName: 'Yegor',
        lastName: 'Koren',
        username: 'purpleowl',
        image: 'https://ca.slack-edge.com/T1MKTR0RX-U8W32Q5PV-551da4900979-512',
        role: 'member',
      },
      {
        _id: '15',
        firstName: 'Alena',
        lastName: 'Zhebrik',
        username: 'alenazhebrik',
        image: 'https://ca.slack-edge.com/T1MKTR0RX-U8X3SHN8J-04c51176886d-512',
        role: 'admin',
      },
    ],
  },
  2: {
    _id: '2',
    type: 'Group',
    name: 'TakeBuddy',
    description: 'OKR is Objectives and Key Results. An approach which is used to try to set ambitious goals and track progress.',
    privacy: 'Private',
    image: 'https://i.imgur.com/xyZ6bj2.png',
    creator: '1',
    parentTeam: '1',
    childTeams: [],
    openGoals: ['1'],
    closeGoals: [],
    members: [
      {
        _id: '1',
        firstName: 'Andrew',
        lastName: 'Orsich',
        username: 'andreworsich',
        image: 'https://trello-avatars.s3.amazonaws.com/23616a42b3226927d6ab9b2fc5905e19/original.png',
        role: 'admin',
      },
      {
        _id: '2',
        firstName: 'Nikita',
        lastName: 'Borww',
        username: 'SobakaSlava',
        image: 'https://ca.slack-edge.com/T1MKTR0RX-U8W543H0C-16591591a0b2-512',
        role: 'member',
      },
      {
        _id: '3',
        firstName: 'Aliona',
        lastName: 'Mozol',
        username: 'alionamozol',
        image: 'https://trello-avatars.s3.amazonaws.com/3695f09f8fdff0ddb23cfa10b5be1e30/original.png',
        role: 'member',
      },
      {
        _id: '4',
        firstName: 'Max',
        lastName: 'Starling',
        username: 'maxstarling',
        image: 'https://ca.slack-edge.com/T1MKTR0RX-U8WAH2YJH-96ec2fb31862-512',
        role: 'member',
      },
      {
        _id: '5',
        firstName: 'Pavel',
        lastName: 'Kalugin',
        username: 'pavelkalugin',
        image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
        email: 'p.kalugin@gmail.com',
        role: 'admin',
      },
      {
        _id: '6',
        firstName: 'Polina',
        lastName: 'Rudenko',
        username: 'polinarudenko',
        image: 'https://ca.slack-edge.com/T1MKTR0RX-U8W2KE6AX-ad9c578b5944-512',
        role: 'member',
      },
      {
        _id: '7',
        firstName: 'Evgeny',
        lastName: 'Marushko',
        username: 'evgenymarushko',
        image: 'https://trello-avatars.s3.amazonaws.com/86cdd1e9a00b6877cf3bf52f68dcd664/170.png',
        role: 'member',
      },
      {
        _id: '8',
        firstName: 'Michael',
        lastName: 'Slizenko',
        username: 'slizenko',
        image: 'https://trello-avatars.s3.amazonaws.com/ac3a1fb8b38af4218aff0873aae688b7/170.png',
        role: 'admin',
      },
    ],
  },
  3: {
    _id: '3',
    type: 'Group',
    name: 'Cycle Service',
    description: 'Cycle Service is a service to provided customers with goods and also to them these products back for recycling purposes.',
    privacy: 'Private',
    image: 'https://i.imgur.com/NcXlnLM.png',
    creator: '1',
    parentTeam: '1',
    childTeams: [],
    openGoals: [],
    closeGoals: [],
    members: [
      {
        _id: '1',
        firstName: 'Andrew',
        lastName: 'Orsich',
        username: 'andreworsich',
        image: 'https://trello-avatars.s3.amazonaws.com/23616a42b3226927d6ab9b2fc5905e19/original.png',
        role: 'admin',
      },
      {
        _id: '8',
        firstName: 'Michael',
        lastName: 'Slizenko',
        username: 'slizenko',
        image: 'https://trello-avatars.s3.amazonaws.com/ac3a1fb8b38af4218aff0873aae688b7/170.png',
        role: 'admin',
      },
      {
        _id: '9',
        firstName: 'Nikita',
        lastName: 'Goncharov',
        username: 'nikitagoncharov',
        image: 'https://ca.slack-edge.com/T1MKTR0RX-U8W543H0C-16591591a0b2-512',
        role: 'member',
      },
      {
        _id: '10',
        firstName: 'Anna',
        lastName: 'Korosteleva',
        username: 'annakorosteleva',
        image: '',
        role: 'member',
      },
      {
        _id: '11',
        firstName: 'Max',
        lastName: 'Mabius',
        username: 'maxmabius',
        image: 'https://trello-avatars.s3.amazonaws.com/b9899ed97c146e9ab0f261bdc6b3c8ea/30.png',
        role: 'member',
      },
      {
        _id: '12',
        firstName: 'Eugene',
        lastName: 'Shved',
        username: 'eugeneshved',
        image: 'https://trello-avatars.s3.amazonaws.com/190f66e38028d732c1922662d5f633ca/30.png',
        role: 'member',
      },
      {
        _id: '13',
        firstName: 'Nikolai',
        lastName: 'Yurkevich',
        username: 'nikolaiyourkevich',
        image: 'https://ca.slack-edge.com/T1MKTR0RX-U8VPH7X6C-745485839eaf-512',
        role: 'member',
      },
      {
        _id: '14',
        firstName: 'Yegor',
        lastName: 'Koren',
        username: 'purpleowl',
        image: 'https://trello-avatars.s3.amazonaws.com/d9b45bcfd7d594dfbcc45c24b9091f34/30.png',
        role: 'member',
      },
      {
        _id: '15',
        firstName: 'Alena',
        lastName: 'Zhebrik',
        username: 'alenazhebrik',
        image: 'https://ca.slack-edge.com/T1MKTR0RX-U8X3SHN8J-04c51176886d-512',
        role: 'admin',
      },
    ],
  },
  32311: {
    _id: '32311',
    type: 'Personal',
    name: 'Pavel Kalugin',
    description: 'This is my personal team',
    privacy: 'Private',
    image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
    creator: '5',
    parentTeam: null,
    childTeams: [],
    openGoals: [
      '97855',
      '51963',
      '50677',
    ],
    closeGoals: [
      '88200',
      '50055',
    ],
    members: [
      {
        _id: '5',
        firstName: 'Pavel',
        lastName: 'Kalugin',
        username: 'by.kalugin',
        role: 'admin',
        image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
      },
    ],
  },
};
