export default {
  mostAppreciatedUser: {
    likeNumber: 111,
    user: {
      _id: '3',
      firstName: 'Aliona',
      lastName: 'Mozol',
      image: 'https://trello-avatars.s3.amazonaws.com/3695f09f8fdff0ddb23cfa10b5be1e30/original.png',
    },
  },
  mostLovedUpdate: {
    title: 'Run OKR product during Startup Winter',
    delta: 20,
    progress: 60,
  },
  overallProgress: {
    progress: 25,
    checkInNumber: 50,
    lastCheckInDate: '2018-03-15T19:31:53+03:00',
  },
  goals: {
    onTrack: 1,
    offTrack: 7,
    none: 2,
  },
  contributors: [
    {
      _id: '3',
      firstName: 'Aliona',
      lastName: 'Mozol',
      username: 'alionamozol',
      image: 'https://trello-avatars.s3.amazonaws.com/3695f09f8fdff0ddb23cfa10b5be1e30/original.png',
      checkInNumber: 12,
      goalNumber: 4,
    },
    {
      _id: '6',
      firstName: 'Polina',
      lastName: 'Rudenko',
      username: 'polinarudenko',
      image: 'https://trello-avatars.s3.amazonaws.com/ea220d8c67e39a887bb45ec1d4f7ff61/original.png',
      checkInNumber: 10,
      goalNumber: 7,
    },
    {
      _id: '5',
      firstName: 'Pavel',
      lastName: 'Kalugin',
      username: 'pavelkalugin',
      image: 'https://trello-avatars.s3.amazonaws.com/671432df54b0d888919c271b174da596/original.png',
      checkInNumber: 20,
      goalNumber: 9,
    },
    {
      _id: '2',
      firstName: 'Nikita',
      lastName: 'Solosniuk',
      username: 'nikitasolosniuk',
      image: 'https://trello-avatars.s3.amazonaws.com/a34f0b51cd60f764c71e7b0965c10a54/original.png',
      checkInNumber: 12,
      goalNumber: 0,
    },
    {
      _id: '4',
      firstName: 'Max',
      lastName: 'Starling',
      username: 'maxstarling',
      image: 'https://ca.slack-edge.com/T1MKTR0RX-U8WAH2YJH-96ec2fb31862-512',
      checkInNumber: 19,
      goalNumber: 2,
    },
    {
      _id: '7',
      firstName: 'Evgeny',
      lastName: 'Marushko',
      username: 'evgenymarushko',
      image: 'https://trello-avatars.s3.amazonaws.com/86cdd1e9a00b6877cf3bf52f68dcd664/170.png',
      checkInNumber: 90,
      goalNumber: 34,
    },

    {
      _id: '8',
      firstName: 'Michael',
      lastName: 'Slizenko',
      username: 'slizenko',
      image: 'https://trello-avatars.s3.amazonaws.com/ac3a1fb8b38af4218aff0873aae688b7/170.png',
      checkInNumber: 10000,
      goalNumber: 12345,
    },
    {
      _id: '1',
      firstName: 'Andrew',
      lastName: 'Orsich',
      username: 'andreworsich',
      image: 'https://trello-avatars.s3.amazonaws.com/23616a42b3226927d6ab9b2fc5905e19/original.png',
      checkInNumber: 13,
      goalNumber: 10,
    },
    {
      _id: '9',
      firstName: 'Cecilia',
      lastName: 'Sanders',
      username: 'cecilia',
      checkInNumber: 0,
      goalNumber: 4,
    },
  ],
};
