import moment from 'moment';

export default {
  1: {
    _id: '1',
    title: 'Create OKR Product During Startup Summer',
    description: 'Create a platform that helps people to clearly define objectives and achieve more at work, at home and in life.',
    startDate: moment('2018-02-22T21:00:00.000Z'),
    endDate: moment('2018-04-06T20:59:59.000Z'),
    parentTeam: '2',
    parentGoal: null,
    progress: 67,
    track: 0,
    assigners: [
      '5',
      '1',
      '2',
      '3',
      '4',
      '7',
      '6',
      '8',
    ],
    status: 'Open',
    totalLikesNumber: 1,
    keyResults: [
      {
        _id: '16616',
        title: 'Present Template',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 80,
      },
      {
        _id: '5068',
        title: 'Implement Design',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 90,
      },
      {
        _id: '1719',
        title: 'Connect Pages To Each Other',
        measure: {
          type: 'numeric',
          from: 0,
          to: 20,
        },
        progress: 20,
      },
      {
        _id: '8178',
        title: 'Test Every Single UI Part',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 61,
      },
      {
        _id: '4728',
        title: 'Present Product on Demo Day',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 0,
      },
    ],
    labels: [],
    checkIns: [
      {
        _id: '7741',
        description: 'Presentation was very nice. We are inspired and ready to make cool product',
        creator: '6',
        date: moment('2018-04-04T13:51:01.697Z'),
        track: 0,
        keyResults: [
          {
            _id: '16616',
            title: 'Present Template',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 80,
            delta: 80,
          },
          {
            _id: '5068',
            title: 'Implement Design',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 0,
            delta: 0,
          },
          {
            _id: '1719',
            title: 'Connect Pages To Each Other',
            measure: {
              type: 'numeric',
              from: 0,
              to: 20,
            },
            progress: 0,
            delta: 0,
          },
          {
            _id: '8178',
            title: 'Test Every Single UI Part',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 0,
            delta: 0,
          },
          {
            _id: '4728',
            title: 'Present Product on Demo Day',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 0,
            delta: 0,
          },
        ],
      },
      {
        _id: '1998',
        description: 'Complete navigation, header and goals',
        creator: '2',
        date: moment('2018-04-04T13:51:33.192Z'),
        track: 0,
        keyResults: [
          {
            _id: '16616',
            title: 'Present Template',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 80,
            delta: 0,
          },
          {
            _id: '5068',
            title: 'Implement Design',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 30,
            delta: 30,
          },
          {
            _id: '1719',
            title: 'Connect Pages To Each Other',
            measure: {
              type: 'numeric',
              from: 0,
              to: 20,
            },
            progress: 2,
            delta: 2,
          },
          {
            _id: '8178',
            title: 'Test Every Single UI Part',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 0,
            delta: 0,
          },
          {
            _id: '4728',
            title: 'Present Product on Demo Day',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 0,
            delta: 0,
          },
        ],
      },
      {
        _id: '1884',
        description: 'Complete main pages',
        creator: '4',
        date: moment('2018-04-04T13:51:53.887Z'),
        track: 0,
        keyResults: [
          {
            _id: '16616',
            title: 'Present Template',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 80,
            delta: 0,
          },
          {
            _id: '5068',
            title: 'Implement Design',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 42,
            delta: 12,
          },
          {
            _id: '1719',
            title: 'Connect Pages To Each Other',
            measure: {
              type: 'numeric',
              from: 0,
              to: 20,
            },
            progress: 6,
            delta: 4,
          },
          {
            _id: '8178',
            title: 'Test Every Single UI Part',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 0,
            delta: 0,
          },
          {
            _id: '4728',
            title: 'Present Product on Demo Day',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 0,
            delta: 0,
          },
        ],
      },
      {
        _id: '660',
        description: 'Complete team pages and input forms',
        creator: '4',
        date: moment('2018-04-04T13:52:17.455Z'),
        track: 0,
        keyResults: [
          {
            _id: '16616',
            title: 'Present Template',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 80,
            delta: 0,
          },
          {
            _id: '5068',
            title: 'Implement Design',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 51,
            delta: 9,
          },
          {
            _id: '1719',
            title: 'Connect Pages To Each Other',
            measure: {
              type: 'numeric',
              from: 0,
              to: 20,
            },
            progress: 14,
            delta: 8,
          },
          {
            _id: '8178',
            title: 'Test Every Single UI Part',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 0,
            delta: 0,
          },
          {
            _id: '4728',
            title: 'Present Product on Demo Day',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 0,
            delta: 0,
          },
        ],
      },
      {
        _id: '2754',
        description: 'Complete all workflow components',
        creator: '2',
        date: moment('2018-04-04T13:52:53.142Z'),
        track: 0,
        keyResults: [
          {
            _id: '16616',
            title: 'Present Template',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 80,
            delta: 0,
          },
          {
            _id: '5068',
            title: 'Implement Design',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 84,
            delta: 33,
          },
          {
            _id: '1719',
            title: 'Connect Pages To Each Other',
            measure: {
              type: 'numeric',
              from: 0,
              to: 20,
            },
            progress: 18,
            delta: 4,
          },
          {
            _id: '8178',
            title: 'Test Every Single UI Part',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 0,
            delta: 0,
          },
          {
            _id: '4728',
            title: 'Present Product on Demo Day',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 0,
            delta: 0,
          },
        ],
      },
      {
        _id: '2229',
        description: 'Crushed design, add bugs',
        creator: '7',
        date: moment('2018-04-04T13:53:16.813Z'),
        track: 1,
        keyResults: [
          {
            _id: '16616',
            title: 'Present Template',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 80,
            delta: 0,
          },
          {
            _id: '5068',
            title: 'Implement Design',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 73,
            delta: -11,
          },
          {
            _id: '1719',
            title: 'Connect Pages To Each Other',
            measure: {
              type: 'numeric',
              from: 0,
              to: 20,
            },
            progress: 20,
            delta: 2,
          },
          {
            _id: '8178',
            title: 'Test Every Single UI Part',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 0,
            delta: 0,
          },
          {
            _id: '4728',
            title: 'Present Product on Demo Day',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 0,
            delta: 0,
          },
        ],
      },
      {
        _id: '3004',
        description: 'Make tests and think about Demo Day',
        creator: '2',
        date: moment('2018-04-04T13:53:37.301Z'),
        track: 0,
        keyResults: [
          {
            _id: '16616',
            title: 'Present Template',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 80,
            delta: 0,
          },
          {
            _id: '5068',
            title: 'Implement Design',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 90,
            delta: 17,
          },
          {
            _id: '1719',
            title: 'Connect Pages To Each Other',
            measure: {
              type: 'numeric',
              from: 0,
              to: 20,
            },
            progress: 20,
            delta: 0,
          },
          {
            _id: '8178',
            title: 'Test Every Single UI Part',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 61,
            delta: 61,
          },
          {
            _id: '4728',
            title: 'Present Product on Demo Day',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 0,
            delta: 0,
          },
        ],
      },
    ],
  },
  2: {
    _id: '2',
    title: 'Succesfully Organise Startup Winter',
    description: '',
    startDate: moment('2018-03-31T21:00:00.000Z'),
    endDate: moment('2018-06-30T20:59:59.999Z'),
    parentTeam: '1',
    parentGoal: null,
    progress: 75,
    track: 0,
    totalLikesNumber: 1,
    assigners: [
      '5', '1', '8', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
    ],
    status: 'Open',
    keyResults: [
      {
        _id: '64504',
        title: 'Prepare Place and Equipment',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 1,
      },
      {
        _id: '3385',
        title: 'Read Lectures & Review Tasks',
        measure: {
          type: 'numeric',
          from: 0,
          to: 17,
        },
        progress: 17,
      },
      {
        _id: '7745',
        title: 'Create OKR Product',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 91,
      },
      {
        _id: '7512',
        title: 'Create Cycle Service Product',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 83,
      },
      {
        _id: '892',
        title: 'Collect Feedback From Students',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
      },
    ],
    labels: [],
    checkIns: [
      {
        _id: '9267',
        description: 'Half lectures are read',
        creator: '1',
        date: moment('2018-04-04T09:14:46.478Z'),
        track: 0,
        keyResults: [
          {
            _id: '64504',
            title: 'Prepare Place and Equipment',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 1,
            delta: 1,
          },
          {
            _id: '3385',
            title: 'Read Lectures & Review Tasks',
            measure: {
              type: 'numeric',
              from: 0,
              to: 17,
            },
            progress: 10,
            delta: 10,
          },
          {
            _id: '7745',
            title: 'Create OKR Product',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 0,
            delta: 0,
          },
          {
            _id: '7512',
            title: 'Create Cycle Service Product',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 0,
            delta: 0,
          },
          {
            _id: '892',
            title: 'Collect Feedback From Students',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 0,
            delta: 0,
          },
        ],
      },
      {
        _id: '5556',
        description: 'All lectures are red. Students have started working on projects',
        creator: '8',
        date: moment('2018-04-04T09:15:32.020Z'),
        track: 0,
        keyResults: [
          {
            _id: '64504',
            title: 'Prepare Place and Equipment',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 1,
            delta: 0,
          },
          {
            _id: '3385',
            title: 'Read Lectures & Review Tasks',
            measure: {
              type: 'numeric',
              from: 0,
              to: 17,
            },
            progress: 17,
            delta: 7,
          },
          {
            _id: '7745',
            title: 'Create OKR Product',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 10,
            delta: 10,
          },
          {
            _id: '7512',
            title: 'Create Cycle Service Product',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 8,
            delta: 8,
          },
          {
            _id: '892',
            title: 'Collect Feedback From Students',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 0,
            delta: 0,
          },
        ],
      },
      {
        _id: '5515',
        description: 'First Demo Presentation',
        creator: '5',
        date: moment('2018-04-04T09:15:48.652Z'),
        track: 0,
        keyResults: [
          {
            _id: '64504',
            title: 'Prepare Place and Equipment',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 1,
            delta: 0,
          },
          {
            _id: '3385',
            title: 'Read Lectures & Review Tasks',
            measure: {
              type: 'numeric',
              from: 0,
              to: 17,
            },
            progress: 17,
            delta: 0,
          },
          {
            _id: '7745',
            title: 'Create OKR Product',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 30,
            delta: 20,
          },
          {
            _id: '7512',
            title: 'Create Cycle Service Product',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 46,
            delta: 38,
          },
          {
            _id: '892',
            title: 'Collect Feedback From Students',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 0,
            delta: 0,
          },
        ],
      },
      {
        _id: '8267',
        description: '2 days due Demo Day',
        creator: '2',
        date: moment('2018-04-04T09:16:15.092Z'),
        track: 0,
        keyResults: [
          {
            _id: '64504',
            title: 'Prepare Place and Equipment',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 1,
            delta: 0,
          },
          {
            _id: '3385',
            title: 'Read Lectures & Review Tasks',
            measure: {
              type: 'numeric',
              from: 0,
              to: 17,
            },
            progress: 17,
            delta: 0,
          },
          {
            _id: '7745',
            title: 'Create OKR Product',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 91,
            delta: 61,
          },
          {
            _id: '7512',
            title: 'Create Cycle Service Product',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 83,
            delta: 37,
          },
          {
            _id: '892',
            title: 'Collect Feedback From Students',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 0,
            delta: 0,
          },
        ],
      },
    ],
  },
  3: {
    _id: '3',
    title: 'Delight our customers',
    description: '',
    startDate: moment('2018-03-31T21:00:00.000Z'),
    endDate: moment('2018-06-30T20:59:59.999Z'),
    parentTeam: '1',
    parentGoal: null,
    progress: 0,
    track: 1,
    totalLikesNumber: 1,
    assigners: [
      '1',
      '5',
      '8',
    ],
    status: 'Open',
    keyResults: [
      {
        _id: '68924',
        title: 'Improve engagement',
        measure: {
          type: 'numeric',
          from: 40,
          to: 60,
        },
        progress: 40,
      },
      {
        _id: '2947',
        title: 'Improve average weekly visits',
        measure: {
          type: 'numeric',
          from: 1000,
          to: 3000,
        },
        progress: 1000,
      },
      {
        _id: '9326',
        title: 'Reduce negative marks',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
      },
    ],
    labels: [],
    checkIns: [],
  },
  4: {
    _id: '4',
    title: 'Cycle Service',
    description: 'Create a platform that helps people to clearly define objectives and achieve more at work, at home and in life.',
    startDate: moment('2018-02-22T21:00:00.000Z'),
    endDate: moment('2018-04-06T20:59:59.000Z'),
    parentTeam: '3',
    parentGoal: null,
    progress: 0,
    track: 2,
    totalLikesNumber: 1,
    assigners: [
      '10',
      '1',
      '12',
      '13',
      '14',
      '11',
      '15',
      '8',
    ],
    status: 'Open',
    keyResults: [
      {
        _id: '23454',
        title: 'Present Template',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
      },
      {
        _id: '6496',
        title: 'Implement Design',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
      },
      {
        _id: '16435',
        title: 'Release Client App',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
      },
      {
        _id: '54364',
        title: 'Release ',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
      },
      {
        _id: '11648',
        title: 'Drivers management solution',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
      },
    ],
    labels: [],
    checkIns: [],
  },
  5: {
    _id: '5',
    title: 'Become a Full Stack Developer',
    description: 'Next step in my life',
    startDate: moment('2018-01-21T21:00:00.000Z'),
    endDate: moment('2018-04-06T20:59:59.000Z'),
    parentTeam: '1',
    parentGoal: null,
    progress: 0,
    totalLikesNumber: 1,
    track: 2,
    assigners: [
      '5',
    ],
    status: 'Open',
    keyResults: [
      {
        _id: '79347',
        title: 'Learn JS&React',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
      },
      {
        _id: '2974',
        title: 'Learn HTML&CSS',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
      },
      {
        _id: '6624',
        title: 'Learn Server Side Tools',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
      },
      {
        _id: '3771',
        title: 'Get to Know Working in Team',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 0,
      },
    ],
    labels: [
      {
        color: 'red',
        content: 'HTML',
      },
      {
        color: 'yellow',
        content: 'JS',
      },
      {
        color: 'blue',
        content: 'CSS',
      },
    ],
    checkIns: [],
  },
  50055: {
    _id: '50055',
    title: 'Read More Books',
    description: 'Reading is very important',
    startDate: moment('2018-03-31T21:00:00.000Z'),
    endDate: moment('2018-06-30T20:59:59.999Z'),
    parentTeam: '32311',
    parentGoal: null,
    progress: 100,
    delta: 0,
    track: 0,
    assigners: [
      '5',
    ],
    totalLikesNumber: 12,
    status: 'Close',
    keyResults: [
      {
        _id: '1',
        title: 'Read a book',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 1,
      },
    ],
    labels: [],
    checkIns: [
      {
        _id: '8084',
        description: '"The Philosophy of Andy Warhol"\nI had amazing time reading this book',
        creator: '5',
        date: moment('2018-04-04T09:16:51.771Z'),
        track: 0,
        keyResults: [
          {
            _id: '1',
            title: 'Read a book',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 1,
            delta: 1,
          },
        ],
      },
      {
        _id: '5043',
        description: '',
        creator: '5',
        date: moment('2018-04-04T09:17:08.731Z'),
        track: 0,
        keyResults: [
          {
            _id: '1',
            title: 'Read a book',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 0,
            delta: -1,
          },
        ],
      },
      {
        _id: '3063',
        description: '"The Philosophy of Andy Warhol"\nI had amazing time reading this book',
        creator: '5',
        date: moment('2018-04-04T09:17:29.699Z'),
        track: 0,
        keyResults: [
          {
            _id: '1',
            title: 'Read a book',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 1,
            delta: 1,
          },
        ],
      },
    ],
  },
  50677: {
    _id: '50677',
    title: 'Become a Full Stack Developer ',
    description: 'Next big step in my life',
    startDate: moment('2018-01-21T21:00:00.000Z'),
    endDate: moment('2018-04-06T20:59:59.000Z'),
    parentTeam: '32311',
    parentGoal: null,
    progress: 82,
    track: 0,
    totalLikesNumber: 1,
    assigners: [
      '5',
    ],
    status: 'Open',
    keyResults: [
      {
        _id: '78522',
        title: 'Learn Frontend, listen to 9 lectures',
        measure: {
          type: 'numeric',
          from: 0,
          to: 9,
        },
        progress: 9,
      },
      {
        _id: '3105',
        title: 'Learn Backend',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 75,
      },
      {
        _id: '6033',
        title: 'Learn devOps',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 1,
      },
      {
        _id: '92',
        title: 'Take active part in product development',
        measure: {
          type: 'percentage',
          from: 0,
          to: 100,
        },
        progress: 50,
      },
    ],
    labels: [
      {
        color: 'red',
        content: 'HTML',
      },
      {
        color: 'yellow',
        content: 'JS',
      },
    ],
    checkIns: [
      {
        _id: '3298',
        description: 'Listened frontend lectures',
        creator: '5',
        date: moment('2018-04-04T09:28:18.349Z'),
        track: 0,
        keyResults: [
          {
            _id: '78522',
            title: 'Learn Frontend, listen to 9 lectures',
            measure: {
              type: 'numeric',
              from: 0,
              to: 9,
            },
            progress: 9,
            delta: 9,
          },
          {
            _id: '3105',
            title: 'Learn Backend',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 0,
            delta: 0,
          },
          {
            _id: '6033',
            title: 'Learn devOps',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 0,
            delta: 0,
          },
          {
            _id: '92',
            title: 'Take active part in product development',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 0,
            delta: 0,
          },
        ],
      },
      {
        _id: '1404',
        description: 'Learned backend a little and tools like docker, webpack, ...',
        creator: '5',
        date: moment('2018-04-04T09:29:07.037Z'),
        track: 0,
        keyResults: [
          {
            _id: '78522',
            title: 'Learn Frontend, listen to 9 lectures',
            measure: {
              type: 'numeric',
              from: 0,
              to: 9,
            },
            progress: 9,
            delta: 0,
          },
          {
            _id: '3105',
            title: 'Learn Backend',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 60,
            delta: 60,
          },
          {
            _id: '6033',
            title: 'Learn devOps',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 1,
            delta: 1,
          },
          {
            _id: '92',
            title: 'Take active part in product development',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 0,
            delta: 0,
          },
        ],
      },
      {
        _id: '7856',
        description: 'Started working on project, improved backend knowledge.',
        creator: '5',
        date: moment('2018-04-04T09:29:57.900Z'),
        track: 0,
        keyResults: [
          {
            _id: '78522',
            title: 'Learn Frontend, listen to 9 lectures',
            measure: {
              type: 'numeric',
              from: 0,
              to: 9,
            },
            progress: 9,
            delta: 0,
          },
          {
            _id: '3105',
            title: 'Learn Backend',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 60,
            delta: 0,
          },
          {
            _id: '6033',
            title: 'Learn devOps',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 1,
            delta: 0,
          },
          {
            _id: '92',
            title: 'Take active part in product development',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 35,
            delta: 35,
          },
        ],
      },
      {
        _id: '7363',
        description: 'Made some useful features',
        creator: '5',
        date: moment('2018-04-04T09:31:17.548Z'),
        track: 0,
        keyResults: [
          {
            _id: '78522',
            title: 'Learn Frontend, listen to 9 lectures',
            measure: {
              type: 'numeric',
              from: 0,
              to: 9,
            },
            progress: 9,
            delta: 0,
          },
          {
            _id: '3105',
            title: 'Learn Backend',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 75,
            delta: 15,
          },
          {
            _id: '6033',
            title: 'Learn devOps',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 1,
            delta: 0,
          },
          {
            _id: '92',
            title: 'Take active part in product development',
            measure: {
              type: 'percentage',
              from: 0,
              to: 100,
            },
            progress: 50,
            delta: 15,
          },
        ],
      },
    ],
  },
  51963: {
    _id: '51963',
    title: 'Spend More Time With Friends & Family',
    description: 'Communication is a key to success',
    startDate: moment('2018-03-31T21:00:00.000Z'),
    endDate: moment('2018-06-30T20:59:59.999Z'),
    parentTeam: '32311',
    parentGoal: null,
    progress: 67,
    delta: 0,
    track: 0,
    assigners: [
      '5',
    ],
    totalLikesNumber: 23,
    status: 'Open',
    keyResults: [
      {
        _id: '1',
        title: 'Meet with friends',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 1,
      },
      {
        _id: '2',
        title: 'Phone parents once a week',
        measure: {
          type: 'numeric',
          from: 0,
          to: 12,
        },
        progress: 4,
      },
    ],
    labels: [],
    checkIns: [
      {
        _id: '5113',
        description: 'Spend weekend in an amusement park with my girlfriend',
        creator: '5',
        date: moment('2018-04-04T09:18:17.427Z'),
        track: 0,
        keyResults: [
          {
            _id: '1',
            title: 'Meet with friends',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 1,
            delta: 1,
          },
          {
            _id: '2',
            title: 'Phone parents once a week',
            measure: {
              type: 'numeric',
              from: 0,
              to: 12,
            },
            progress: 4,
            delta: 4,
          },
        ],
      },
    ],
  },
  88200: {
    _id: '88200',
    title: 'Make a step toward setting up your personal goals',
    description: 'We will make TakeBuddy using TakeBuddy',
    startDate: moment('2018-03-31T21:00:00.000Z'),
    endDate: moment('2018-06-30T20:59:59.999Z'),
    parentTeam: '32311',
    parentGoal: null,
    progress: 100,
    delta: 0,
    track: 2,
    assigners: [
      '5',
    ],
    totalLikesNumber: 14,
    status: 'Close',
    keyResults: [
      {
        _id: '1',
        title: 'Sign up for TakeBuddy',
        measure: {
          type: 'boolean',
          from: 0,
          to: 1,
        },
        progress: 1,
      },
    ],
    labels: [],
    checkIns: [
      {
        _id: '17691',
        description: 'Welcome to TakeBuddy! Get started by reviewing and setting your goals.',
        creator: '5',
        date: moment('2018-04-04T09:13:45.060Z'),
        track: 0,
        keyResults: [
          {
            _id: '1',
            title: 'Sign up for TakeBuddy',
            measure: {
              type: 'boolean',
              from: 0,
              to: 1,
            },
            progress: 1,
            delta: 1,
          },
        ],
      },
    ],
  },
  97855: {
    _id: '97855',
    title: 'Give Up On The Unhealthy Lifestyle',
    description: 'I\'m starting new life',
    startDate: moment('2018-03-31T21:00:00.000Z'),
    endDate: moment('2018-06-30T20:59:59.999Z'),
    parentTeam: '32311',
    parentGoal: null,
    progress: 0,
    delta: 0,
    track: 2,
    assigners: [
      '5',
    ],
    totalLikesNumber: 33,
    status: 'Open',
    keyResults: [
      {
        _id: '1',
        title: 'Exercise three times a week',
        measure: {
          type: 'numeric',
          from: 0,
          to: 36,
        },
        progress: 0,
      },
      {
        _id: '2',
        title: 'Eat healthy food every day',
        measure: {
          type: 'numeric',
          from: 0,
          to: 87,
        },
        progress: 0,
      },
    ],
    labels: [],
    checkIns: [],
  },
};
